var bankName;
bankName = 'SBI Bank';
console.log(bankName);
console.log(typeof bankName);
var mark ='90%';
console.log(mark);
console.log(typeof mark);
 var isWorking;
 isWorking = true;
 console.log(isWorking);
 console.log(typeof isWorking);
 var totalCount = 'Hunderd and Seven';
 console.log(totalCount);
 console.log(typeof totalCount);
 totalCount = 107;
 console.log(totalCount);
 console.log(typeof totalCount);
